export interface PetData {
    id: string;
    title: string;
    badge: string;
    badgeStyle: string;
    district: string;
    features: string;
    date: string;
    age: string;
    race: string;
    gender: string;
    reward: string;
    views: string;
    shares: string;
    desc: string;
    imgSrc: string;
    images?: string[]
    isPremium?: boolean;
    isExternal?: boolean;
    externalType?: 'instagram' | 'tiktok' | 'facebook' | 'google';
    externalUrl?: string;
}

export const allPets: PetData[] = [
    {
        id: 'benji-14',
        title: 'Benji (Poodle toy)',
        badge: 'Perdido',
        badgeStyle: 'badge-urgent',
        district: 'Lima, Miraflores',
        features: 'Poodle toy color blanco',
        date: '04 Jul 2026, 3:01 pm',
        age: '1-2 años',
        race: 'Pitbull',
        gender: 'Macho (Castrado)',
        reward: 'S/. 1,000',
        views: '7',
        shares: '4',
        desc: 'Benji es muy asustadizo, lleva un collar azul. Se escapó corriendo con dirección al óvalo de Miraflores.',
        imgSrc: '/uploads/publicaciones/dog-14.jpg',
    },
    {
        id: 'gata-carey-con-collar-morado',
        title: 'Gata Carey con collar morado',
        badge: 'Encontrado',
        badgeStyle: 'badge-found',
        district: 'Surco',
        features: 'Poodle toy color blanco',
        date: '17 Ene 2026, 5:17 pm',
        age: '1-2 años',
        race: 'Pitbull',
        gender: 'Macho (Castrado)',
        reward: 'S/. 1,000',
        views: '14',
        shares: '7',
        desc: 'Benji es muy asustadizo, lleva un collar azul.',
        imgSrc: '/uploads/publicaciones/dog-2.jpg',
    },
    {
        id: 'gata-carey-vista',
        title: 'Gata Carey con collar morado',
        badge: 'Avistamiento',
        badgeStyle: 'badge-sight',
        district: 'Miraflores',
        features: 'Poodle toy color blanco',
        date: '4 de Mayo 2024',
        age: '1-2 años',
        race: 'Pitbull',
        gender: 'Macho (Castrado)',
        reward: '',
        views: '7',
        shares: '10',
        desc: 'Benji es muy asustadizo, lleva un collar azul.',
        imgSrc: '/uploads/publicaciones/dog-3.jpg',
    },
    {
        id: 'thor-husky-molina-1',
        title: 'Thor (Husky de 1 año)',
        badge: 'Urgente',
        badgeStyle: 'badge-max-priority',
        district: 'La Molina',
        features: 'Husky siberiano, ojos azules',
        date: '04 Jul 2026, 3:01 pm',
        age: '1-2 años',
        race: 'Pitbull',
        gender: 'Macho (Castrado)',
        reward: 'S/. 2,500',
        views: '10',
        shares: '41',
        desc: 'Benji es muy asustadizo, lleva un collar azul.',
        imgSrc: '/uploads/publicaciones/dog-4.jpg',
        isPremium: true,
    },
    {
        id: 'benji-5',
        title: 'Benji (Poodle toy)',
        badge: 'Perdido',
        badgeStyle: 'badge-urgent',
        district: 'Miraflores',
        features: 'Poodle toy color blanco',
        date: '14 Jul 2026, 7:04 pm',
        age: '1-2 años',
        race: 'Pitbull',
        gender: 'Macho (Castrado)',
        reward: '',
        views: '1',
        shares: '0',
        desc: 'Benji es muy asustadizo, lleva un collar azul.',
        imgSrc: '/uploads/publicaciones/dog-5.jpg',
    },
    {
        id: 'gata-carey-collar-morado-2',
        title: 'Gata Carey con collar morado',
        badge: 'Encontrado',
        badgeStyle: 'badge-found',
        district: 'Lima',
        features: 'Carey (tricolor), pelo corto',
        date: '04 Jul 2026, 3:01 pm',
        age: '2-3 años',
        race: 'Mestizo (gata)',
        gender: 'Hembra',
        reward: '',
        views: '47',
        shares: '117',
        desc: 'Fue encontrada deambulando cerca del Parque de Surco. Está bien de salud, es tranquila.',
        imgSrc: '/uploads/publicaciones/dog-6.jpg',
    },
    {
        id: 'ext-instagram-1',
        title: 'Snauser gris con corte reciente',
        badge: 'Instagram',
        badgeStyle: 'badge-ext-instagram',
        district: 'San Isidro',
        features: '',
        date: '17 Jul 2026, 3:01 pm',
        age: '',
        race: '',
        gender: '',
        reward: '',
        views: '0',
        shares: '0',
        desc: '',
        imgSrc: '/uploads/publicaciones/dog-15.jpg',
        isExternal: true,
        externalType: 'instagram',
        externalUrl: 'https://www.instagram.com/p/C_instagram_post_url/',
    },
    {
        id: 'perrito-asustado-7',
        title: 'Perrito corriendo asustado en Av. Principal',
        badge: 'Avistamiento',
        badgeStyle: 'badge-sight',
        district: 'Miraflores',
        features: 'Poodle toy color blanco',
        date: '4 de Mayo 2024',
        age: '1-2 años',
        race: 'Pitbull',
        gender: 'Macho (Castrado)',
        reward: '',
        views: '9',
        shares: '4',
        desc: 'Benji es muy asustadizo, lleva un collar azul.',
        imgSrc: '/uploads/publicaciones/dog-7.jpg',
    },
    {
        id: 'thor-husky-molina-2',
        title: 'Thor (Husky de 1 año)',
        badge: 'Urgente',
        badgeStyle: 'badge-max-priority',
        district: 'La Molina',
        features: 'Husky siberiano, ojos azules',
        date: '04 Jul 2026, 3:01 pm',
        age: '1 año',
        race: 'Husky Siberiano',
        gender: 'Macho',
        reward: 'S/. 1,500',
        views: '47',
        shares: '47',
        desc: 'Thor se escapó por la puerta trasera.',
        imgSrc: '/uploads/publicaciones/dog-8.jpg',
        isPremium: true,
    },
    {
        id: 'max-adopcion-1',
        title: 'Max (Labrador joven)',
        badge: 'En adopción',
        badgeStyle: 'badge-adopt',
        district: 'Miraflores',
        features: 'Labrador color miel, pelo corto',
        date: 'Hoy, 3:01 pm',
        age: '8 meses',
        race: 'Labrador',
        gender: 'Macho',
        reward: '',
        views: '4',
        shares: '0',
        desc: 'Max llegó a nosotros luego de ser rescatado de la calle.',
        imgSrc: '/uploads/publicaciones/dog-10.jpg',
    },
    {
        id: 'thor-husky-molina-3',
        title: 'Thor (Husky de 1 año)',
        badge: 'Urgente',
        badgeStyle: 'badge-max-priority',
        district: 'La Molina',
        features: 'Husky siberiano, ojos azules',
        date: '04 Jul 2026, 3:01 pm',
        age: '1 año',
        race: 'Husky Siberiano',
        gender: 'Macho',
        reward: 'S/. 1,500',
        views: '3,210',
        shares: '780',
        desc: 'Thor se escapó por la puerta trasera.',
        imgSrc: '/uploads/publicaciones/dog-1.jpg',
        isPremium: true,
    },
    {
        id: 'ext-tiktok-1',
        title: 'Gatito herido reportado en video viral',
        badge: 'Tiktok',
        badgeStyle: 'badge-ext-tiktok',
        district: 'Lince',
        features: '',
        date: '04 Jul 2026, 3:01 pm',
        age: '',
        race: '',
        gender: '',
        reward: '',
        views: '0',
        shares: '0',
        desc: '',
        imgSrc: '/uploads/publicaciones/dog-11.jpg',
        isExternal: true,
        externalType: 'tiktok',
        externalUrl: 'https://www.tiktok.com/@user/video/123456789',
    },
    {
        id: 'thor-husky-molina-4',
        title: 'Thor (Husky de 1 año)',
        badge: 'Urgente',
        badgeStyle: 'badge-max-priority',
        district: 'La Molina',
        features: 'Husky siberiano, ojos azules',
        date: '04 Jul 2026, 3:01 pm',
        age: '1 año',
        race: 'Husky Siberiano',
        gender: 'Macho',
        reward: 'S/. 1,500',
        views: '24',
        shares: '74',
        desc: 'Thor se escapó por la puerta trasera.',
        imgSrc: '/uploads/publicaciones/dog-9.jpg',
        isPremium: true,
    },
    {
        id: 'max-adopcion-2',
        title: 'Max (Labrador joven)',
        badge: 'En adopción',
        badgeStyle: 'badge-adopt',
        district: 'Miraflores',
        features: 'Labrador color miel, pelo corto',
        date: 'Hoy, 3:01 pm',
        age: '8 meses',
        race: 'Labrador',
        gender: 'Macho',
        reward: '',
        views: '17',
        shares: '36',
        desc: 'Max llegó a nosotros luego de ser rescatado de la calle.',
        imgSrc: '/uploads/publicaciones/dog-3.jpg',
    },
    {
        id: 'ext-facebook-1',
        title: 'Gatito naranja visto en zona de parque',
        badge: 'Facebook',
        badgeStyle: 'badge-ext-facebook',
        district: 'Miraflores',
        features: '',
        date: '04 Jul 2026, 3:01 pm',
        age: '',
        race: '',
        gender: '',
        reward: '',
        views: '0',
        shares: '0',
        desc: 'Reportado por un usuario en grupo público de Facebook de la zona.',
        imgSrc: '/uploads/publicaciones/dog-10.jpg',
        isExternal: true,
        externalType: 'facebook',
        externalUrl: 'https://facebook.com/url-del-post-original',
    },
];