// ==========================================================
// SUGERENCIAS PARA EL FORMULARIO DE PUBLICACIÓN
// ==========================================================

export const RAZAS_PERRO: string[] = [
    'Mestizo',
    'Criollo',
    'Labrador',
    'Golden Retriever',
    'Pastor Alemán',
    'Bulldog Francés',
    'Bulldog Inglés',
    'Chihuahua',
    'Poodle',
    'Poodle Toy',
    'Schnauzer',
    'Beagle',
    'Boxer',
    'Cocker',
    'Shitzu',
    'Yorkshire',
    'Pug',
    'Husky',
    'Dálmata',
    'Doberman',
    'Rottweiler',
    'Border Collie',
    'Salchicha',
    'Maltés',
    'Pit Bull',
    'Pekinés',
    'Basset Hound',
    'Akita',
    'San Bernardo',
    'Gran Danés',
    'Perro sin pelo',
    'Pomerania',
    'Pinscher',
    'American Bully',
    'Siberiano',
    'Pastor Belga',
    'Cane Corso',
    'Chow Chow',
    'Shar Pei',
    'Jack Russell',
    'Dogo Argentino',
    'Terrier Brasileño',
    'Xoloitzcuintle'
];

export const RAZAS_GATO: string[] = [
    'Mestizo / Criollo',
    'Persa',
    'Siamés',
    'Angora',
    'Maine Coon',
    'Bengalí',
    'Británico',
    'Ragdoll',
    'Esfinge',
    'Himalayo',
    'Abisinio',
    'Azul Ruso',
    'Munchkin',
    'Scottish Fold',
    'Birmano',
    'Burmés',
    'Bombay',
    'Exótico',
    'Siberiano',
    'Somalí',
    'Oriental',
    'Manx',
    'Toyger',
];

export const ESPECIES_AVE: string[] = [
    'Periquito',
    'Perico',
    'Loro',
    'Amazonas',
    'Cacatúa',
    'Canario',
    'Agapornis',
    'Ninfa',
    'Paloma',
    'Gallina',
    'Guacamayo',
    'Pavo',
    'Pavo Real',
    'Diamante',
    'Finch',
    'Jilguero',
    'Calopsita',
    'Gorrión',
    'Tórtola',
    'Pato',
    'Ganso',
];

export const COLORES_PELAJE: string[] = [
    'Negro',
    'Blanco',
    'Gris',
    'Marrón',
    'Café',
    'Beige',
    'Crema',
    'Dorado',
    'Canela',
    'Rojizo',
    'Atigrado',
    'Manchado',
    'Tricolor',
    'Blanco y negro',
    'Blanco y marrón',
    'Negro y blanco',
    'Gris y blanco',
    'Marrón y blanco',
    'Negro y marrón',
];

export const COLORES_PLUMAJE: string[] = [
    'Verde',
    'Amarillo',
    'Azul',
    'Blanco',
    'Gris',
    'Celeste',
    'Negro',
    'Rojo',
    'Naranja',
    'Marrón',
    'Café',
    'Violeta',
    'Rosado',
    'Multicolor',
    'Verde y amarillo',
    'Azul y blanco',
    'Amarillo y azul',
    'Verde y azul',
];
